### ISSUE TITLE
Give more information about the entity, taxonomy term etc.

### ISSUE THREAD

**Issue by MoeHome** [serlo/notification-mail-service#11]
information we need to send the email:

- [x] user email
- [x] username

for each notification: 
       
- [x] actor_name with link
- [x] event_type
- [x] properties specific to the event_type
- [x] date

**Comment by MoeHome** [comment]
My plan is to fetch user email, name, event_id and event_type from the database. And then make an API call for all the relevant event information.

**Comment by CarolinJaser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Umzug Send E-mails](https://trello.com/c/11vuQnAT/13-umzug-send-e-mails)

**Comment by CarolinJaser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Umzug Send E-mails](https://trello.com/c/11vuQnAT/13-umzug-send-e-mails)

**Comment by hugotiburtino** [comment]
Closed via #18
