### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/notification-mail-service#4]
- [ ] Make a working Dockerfile that already runs the notification functionality (since it is going to be integrated as a cronjob)
- [ ] Script for pushing the image that tags it according the version in the `package.json` file.
- [ ] Maybe build the source code for productive use (optional)

Waiting for 
- [x] https://github.com/serlo/notification-mail-service/issues/1

**Comment by CarolinJaser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Umzug Send E-mails](https://trello.com/c/11vuQnAT/13-umzug-send-e-mails)
