### ISSUE TITLE
Follow up: complete basic implementation and apply best practices

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/notification-mail-service#5]
Follow up of https://github.com/serlo/notification-mail-service/pull/3

- [x] #11
- [x] #8
- [x] Improve code in some places (v.g. [here](https://github.com/serlo/notification-mail-service/blob/d916438d0dd6baca26aacf5bdddbaa55d7f6c343/src/services/mail-service.ts#L49-L71))
- [x] Add unit and/or integration tests
- [x] Apply typescript best practices
- [x] Maybe start getting some information from API (since in the future this service won't have direct connection to database)
- [x] Simplify code structure making it a script (all we need now is a script, that we could call directly. A server that works as an API may be an idea for the future, if at all)
- [x] #10
- [ ] Nice to have: do not send comment that was trashed

Some possible inspirations:
- [serlo.org-legacy/packages/public/notifications-job/src/index.ts](https://github.com/serlo/serlo.org-legacy/blob/48e687d59a62b6d8ab638bf7735b6c25df27e728/packages/public/notifications-job/src/index.ts)
- [For SQL query](https://github.com/serlo/serlo.org-legacy/blob/5a3a5ead8372f7233c867ef3215444b43d4574b7/packages/public/server/src/module/Notification/src/NotificationManager.php#L90)
- [logic of legacy](https://github.com/serlo/serlo.org-legacy/blob/main/packages/public/server/src/module/Mailman/src/Listener/NotificationWorkerListener.php)
- [For the email body](https://github.com/serlo/serlo.org-legacy/tree/5a3a5ead8372f7233c867ef3215444b43d4574b7/packages/public/server/src/module/Ui/templates/mailman/messages/notification)
- [frontend notification page](https://github.com/serlo/frontend/blob/staging/src/pages/user/notifications.tsx)
- [frontend notification component](https://github.com/serlo/frontend/blob/staging/src/components/pages/user/notifications.tsx)
- [frontend query for getting notification events](https://github.com/serlo/frontend/blob/staging/src/fetcher/query-fragments.ts#L58-L280)
- [how frontend renders each event](https://github.com/serlo/frontend/blob/43349ba743cb7be0bb4a4247e682365898a5893a/src/components/user/event.tsx)

**Comment by CarolinJaser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Umzug Send E-mails](https://trello.com/c/11vuQnAT/13-umzug-send-e-mails)
