### ISSUE TITLE
Refactor: Consistent database handle

### ISSUE THREAD

**Issue by MoeHome** [serlo/notification-mail-service#9]
The database handle connection should be opened and closed in the main function. It provides the connection to the functions which need it.

**Comment by hugotiburtino** [comment]
Closed via #13

**Comment by CarolinJaser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Umzug Send E-mails](https://trello.com/c/11vuQnAT/13-umzug-send-e-mails)
